overblog_graphql_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"

# overblog_graphiql_endpoint:
#     resource: "@OverblogGraphiQLBundle/Resources/config/routing.xml"
